var fs = require('fs');
var c = [];
c.push("'use client'");
c.push("import { useEffect, useRef } from 'react'");
c.push("");
c.push("type ActivityEvent = { type: 'add' | 'update' | 'delete'; time: number }");
c.push("");
c.push("export default function ActivityCanvas({ events }: { events: ActivityEvent[] }) {");
c.push("  const canvasRef = useRef<HTMLCanvasElement>(null)");
c.push("");
c.push("  useEffect(() => {");
c.push("    const canvas = canvasRef.current");
c.push("    if (!canvas) return");
c.push("    const ctx = canvas.getContext('2d')");
c.push("    if (!ctx) return");
c.push("");
c.push("    ctx.clearRect(0, 0, canvas.width, canvas.height)");
c.push("");
c.push("    const barWidth = 30");
c.push("    const gap = 10");
c.push("    const maxBars = Math.floor(canvas.width / (barWidth + gap))");
c.push("    const visible = events.slice(-maxBars)");
c.push("");
c.push("    visible.forEach(function(event, i) {");
c.push("      const x = i * (barWidth + gap) + gap");
c.push("      const height = 60 + Math.random() * 40");
c.push("      const y = canvas.height - height - 10");
c.push("");
c.push("      if (event.type === 'add') ctx.fillStyle = '#22c55e'");
c.push("      else if (event.type === 'update') ctx.fillStyle = '#3b82f6'");
c.push("      else ctx.fillStyle = '#ef4444'");
c.push("");
c.push("      ctx.beginPath()");
c.push("      ctx.roundRect(x, y, barWidth, height, 4)");
c.push("      ctx.fill()");
c.push("");
c.push("      ctx.fillStyle = '#6b7280'");
c.push("      ctx.font = '9px sans-serif'");
c.push("      ctx.textAlign = 'center'");
c.push("      const label = event.type === 'add' ? '+' : event.type === 'update' ? '~' : '-'");
c.push("      ctx.fillText(label, x + barWidth / 2, canvas.height - 2)");
c.push("    })");
c.push("");
c.push("    if (visible.length === 0) {");
c.push("      ctx.fillStyle = '#9ca3af'");
c.push("      ctx.font = '13px sans-serif'");
c.push("      ctx.textAlign = 'center'");
c.push("      ctx.fillText('No activity yet. Add a note to see live chart!', canvas.width / 2, canvas.height / 2)");
c.push("    }");
c.push("  }, [events])");
c.push("");
c.push("  return (");
c.push("    <canvas");
c.push("      ref={canvasRef}");
c.push("      width={600}");
c.push("      height={120}");
c.push("      className='w-full rounded-xl bg-gray-50 border border-gray-200'");
c.push("    />");
c.push("  )");
c.push("}");
fs.writeFileSync('app/components/ActivityCanvas.tsx', c.join('\n'), 'utf8');
console.log('Done!');
